name: musa-550-fall-2021
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy=1.21.2
  - nodejs=16.6.1
  - black=21.7b0
  - jupyterlab_code_formatter=1.4.10
  - pandas=1.3.2
  - openpyxl=3.0.7
  - matplotlib=3.4.3
  - notebook=6.4.3
  - ipython=7.27.0
  - jupyterlab=3.1.9
  - nbconvert=5.6.1
  - pip=21.2.4
  - altair=4.1.0
  - seaborn=0.11.2
  - vega_datasets=0.9.0
  - vega=3.5.0
  - geopandas=0.10.2
  - shapely=1.7.1
  - descartes=1.1.0
  - pyepsg=0.4.0
  - cartopy=0.19.0.post1
  - mapclassify=2.4.3
  - contextily=1.1.0
  - bokeh=2.3.3
  - hvplot=0.7.3
  - holoviews=1.14.5
  - geoviews=1.9.1
  - xarray=0.19.0
  - datashader=0.13.0
  - param=1.11.1
  - panel=0.12.1
  - rasterio=1.2.6
  - rasterstats=0.15.0
  - earthpy=0.9.2
  - requests=2.26.0
  - cenpy=1.0.0.post4
  - selenium=3.141.0
  - beautifulsoup4=4.9.3
  - geckodriver=0.29.1
  - imageio=2.9.0
  - intake=0.6.3
  - intake-parquet=0.2.3
  - intake-xarray=0.5.0
  - dask=2021.8.1
  - fastparquet=0.7.1
  - python-snappy=0.6.0
  - pyarrow=4.0.0
  - s3fs=2021.8.0
  - tqdm=4.62.2
  - pandana=0.6.1
  - osmnet=0.1.6
  - osmnx=1.1.1
  - networkx=2.6.2
  - scikit-learn=0.24.2
  - flask=2.0.1
  - dash=1.21.0
  - tweepy=3.10.0
  - textblob=0.15.3
  - nltk=3.6.2
  - rio-toa=0.3.0
  - rioxarray=0.7.0
  - missingno=0.4.2
  - kneed=0.7.0
  - pip:
      - us==2.0.2
      - carto2gpd==1.0.11
      - esri2gpd==1.0.12
      - osm2gpd==1.0.1
      - webdriver_manager==3.4.2
      - jupyter-panel-proxy==0.1.0
      - jupyter-server-proxy==3.1.0
